### ISSUE TITLE
test hosting svg icons for FLM engagement

### ISSUE THREAD

**Issue by thuang579** [LACMTA/community-engagement#3]

**Comment by thuang579** [comment]
Paper [doc link](https://paper.dropbox.com/doc/Metro-Custom-Basemap-and-FLM-Symbology--BVFj1SHRiJv581hR1fT94BYWAg-ZKuxLPhflkYfav21ilw1b#:uid=489949989762490708082140&h2=Files-for-testing-PNGs-vs-SVGs) – thanks!

**Comment by matikin9** [comment]
@albertkun - I think this might fit in the documentation repo?
