### ISSUE TITLE
GIS Day Planning

### ISSUE THREAD

**Issue by albertkun** [LACMTA/community-engagement#5]
# Ideas
## External ideas
- [ ] Metro presentation
- [ ] Create a cool map to share with communities
- [ ] Metro Basemap (potentially?)
- [ ] Shapefiles
- [ ] GTFS
- [ ] share current mapping projects at Metro

## Internal facing

- [ ] Present ways to use maps 
- [ ] Present Metro basemap
- [ ] share mapping projects at Metro

## Potential Contacts
- Rollin
- Anika
- Kenneth

**Comment by matikin9** [comment]
LA County GIS Day: https://la-county-gis-day.heysummit.com/

MaptimeLA Repositories (workshops, projects, etc.): https://github.com/maptimela

Neighborhood Haikus Map: https://github.com/maptimeLA/neighborhoods
http://maptimela.github.io/neighborhoods/
![image](https://user-images.githubusercontent.com/1873072/140435639-5e1ed073-fbc7-4c5d-a047-cffb69da3927.png)

**Comment by matikin9** [comment]
BUFFET of GIS - lightning talks...

What's the relevance of maps and GIS to Marketing folks?

Could this lead into further workshops/talks as a series.

Focus on data?!

**Comment by matikin9** [comment]
Theme-based: Centralization (Unity?)

GIS-Day to kick off a Mapping series

Make sure each session has a takeaway connecting it to the next session.

1. For the Love of Maps (GIS Day)
    * Show & Tell lightning talks
    * Open Call for contributions
    * Next: how to contribute to a map yourself!
2. Humanitarian Mapping
    * OSM editing
    * HOTOSM contribution
    * Next: connect to justice?
3. Maps and Justice
    * Indigenous Mapping
    * Redlining
    * Next: our work at Metro?
4. OneMAP
    * Metro efforts
    * Using ESRI/ArcGIS to build your own maps
    * Next: ???

Next Steps: 

- [x] Think about the order & how to logically connect the sessions.
- [x] Put together email & Google Form for submissions (deadline by Monday, Nov 15).
- [x] Send out Calendar invite by EOD ~Friday 11/5/21~ Monday 11/8/21 as an official Lunch & Learn.
- [ ] ~Put together instructions on how to put it onto GitHub.~
- [ ] Metro GIS Guild?!?!

**Comment by albertkun** [comment]
# Meeting Notes 11/4/2021

## Albert
General ideas of maps, why they are important

## Nina
Marketing focus

## Tiffany
- GitHub workshop (get familiar)
- Love the idea of a series
- "Lets empower people spatially"
- Going beyond just maps and to data!

## Lightning Talks
### The main idea: taking it beyond just OneMap, one map is just one piece of a puzzle?
### Centralized-location?
- Allow for solicitations
-

**Comment by matikin9** [comment]
Rough Agenda - 12:05pm-1pm (55 min)

Intro - For the Love of Maps! (5 min) Albert
- GIS Day background
- Today's session
- Throw comments/questions into the chat and we will monitor.

Nina - 4 maps (10 min - 12:10 to 12:20pm)
- AuthaGraph World Map - http://www.authagraph.com/
  - Map Projections - http://practicalgeoskills.blogspot.com/2020/04/map-projections-meaning-and-examples.html
  - West Wing clip - https://www.youtube.com/watch?v=eLqC3FNNOaI
- The Gerry-mander - https://www.smithsonianmag.com/history/where-did-term-gerrymander-come-180964118/
  - Princeton Gerrymandering Project - https://gerrymander.princeton.edu/
- NY trip Google Map - https://www.google.com/maps/d/u/0/edit?mid=1IjigPbzmxtDS61vXkvBFWbZvL3k&ll=40.71721296064129%2C-74.03298136321447&z=13
- Arts Datathon Community Crafting + Mapping - https://github.com/matikin9/arts-datathon-3-crafting
- built:LA - https://github.com/cityhubla/LA_Building_Age
- NY MTA Live Map - https://map.mta.info/#@40.70949,-73.97853,14z

Holly Hampton (5 min)
- SELA Community Map

Tiffany's map(s) (5 min)
- You Matter map
- Wisley Walks map

Albert (25 min - 12:30pm)
- poll the audience


Wrap up (5 min) Nina
- Making your own map (OSM, Google Maps, ArcGIS)
- Upcoming Lunch & Learns: Humanitarian Mapping, Maps & Justice, OneMAP & ESRI/ArcGIS
- Closing poll - 

camping images?

**Comment by matikin9** [comment]
Created separate issues for GIS Events 2, 3, and 4.
